### ISSUE TITLE
Wishlist: option to set map legend opacity according to layer opacity

### ISSUE THREAD

**Issue by hatapitk** [oskariorg/oskari-frontend#34]
Map layers are often opaque and need some transparency so that they can be viewed together with the background map. Currently user can adjust the layer transparency easily. The map legend is not affected by the opacity setting and this may make it harder for user to see how colors in the legend match the semi-transparent colors on the map. It would be nice to have an option that, when enabled, would force the legend transparency to follow layer transparency. There are downsides in this (highly transparent legend text would become hard to read) but in typical use cases (50 % transparency) this might work well enough for applications that need it.

**Comment by ZakarFin** [comment]
Nice idea. The UI could offer a toggle to see the legend with corresponding maplayer opacity or as is.

**Comment by ZakarFin** [comment]
@hatapitk Can you repost this to https://github.com/oskariorg/oskari-docs/issues. We are in process of disabling issues on the other repositories
