### ISSUE TITLE
Sample application separation

### ISSUE THREAD

**Issue by posikifi** [oskariorg/oskari-frontend#7]
Hi!

I really like if you can separate sample application from real code. Now you have to download and install whole Oskari to play with sample applications. 

My suggestion is that all sample application will have direct links to somewhere in the net, where is Oskari-libraries already up and running. Compare this to Openlayers sample applications.

P

**Comment by ZakarFin** [comment]
This will hopefully remedy the situation https://github.com/oskariorg/oskari-docs/issues/39
